#config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
  documentation:
    #        schemes: [http, https]
    info:
      title: PentaBee API
      description: PentaBee API Documentation
      version: 1.0.0
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Authorization: Bearer {jwt}'
        name: Authorization
        in: header
    security:
      - Bearer: []
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc